# A configuration file for the MLEM-MPI.py execution
NImgX: 180
NImgY: 180
NDetY: 32
NModule: 6
NDetX: 8
system matrix bin files folder: /panasas/scratch/grp-rutaoyao/1101
N input files: 50
matrix N-divide: 2 
N iterations: 8000
reconstruction storage scale factor: 10
# phantom file: contrast-phantom-nobg.npz
# out npz filename: recon-out-iter-2000.npz
# phantom file: contrast-phantom.npz
# out npz filename: recon-out-iter-2000-contrast-phantom.npz
phantom file: bg-phantom.npz
out npz filename: recon-out-iter-8000-bg-phantom.npz
